# Generated by Django 3.0.7 on 2020-06-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_info',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_register.personal_info'),
        ),
    ]
