# Generated by Django 3.0.7 on 2020-06-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20200618_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_info',
            name='job_description',
            field=models.CharField(choices=[('sr', 'Sr. Software Eng.'), ('mi', 'Software Eng.'), ('jr', 'Sr. Software Eng.'), ('in', 'Intern Software Eng.')], default='sr', max_length=5),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=5),
        ),
    ]
